//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kirjautuminen___DataBase.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YdinvoimalaDBEntities : DbContext
    {
        public YdinvoimalaDBEntities()
            : base("name=YdinvoimalaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kirjaukset> Kirjaukset { get; set; }
        public virtual DbSet<Työntekijät> Työntekijät { get; set; }
    }
}
